name: Run django check
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  django_check:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run check
      run: python manage.py check
    - name: Run tests
      run: python manage.py test
